include:
  - user/compose.yaml
  - auth/compose.yaml
  
services:
#   config-server:
#     build: ./config-server
#     container_name: config-server
#     ports:
#       - "8888:8888"
#     environment:
#       - SPRING_PROFILES_ACTIVE=docker
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
#       interval: 10s
#       timeout: 5s
#       retries: 5
#     networks:
#       - spring-net

  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    # depends_on:
    #   config-server:
    #     condition: service_healthy
    # environment:
      # - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      # - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka
    environment:
      # - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - EUREKA_SERVER_URI=http://eureka:8761/eureka
    networks:
      - spring-net

  servicea:
    build: ./servicea
    container_name: servicea
    depends_on:
      - eureka
      - servicea-pg
    ports:
      - "8081:8080"
    networks:
      - spring-net
    environment:
      - EUREKA_SERVER_URI=http://eureka:8761/eureka

  servicea-pg:
    image: 'postgres:17'
    container_name: 'servicea-pg'
    ports:
      - "5483:5432"
    networks:
      - spring-net
    environment:
      POSTGRES_DB: 'ead_db'
      POSTGRES_USER: 'ead_user'
      POSTGRES_PASSWORD: 'ead_pwd'

  serviceb:
    build: 
      context: ./serviceb
      secrets:
        - github-username
        - github-token
    container_name: serviceb
    depends_on:
      - eureka
    ports:
      - "8082:8080"
    networks:
      - spring-net
    environment:
      - EUREKA_SERVER_URI=http://eureka:8761/eureka

#   auth-service:
#     build: ./auth-service
#     container_name: auth-service
#     ports:
#       - "8083:8083"
#     depends_on:
#       - eureka-server
#       - config-server
#     environment:
#       - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
#       - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
#     networks:
#       - spring-net

networks:
  spring-net:
    driver: bridge

secrets:
  github-username:
    environment: ${GITHUB_USERNAME}
  github-token:
    environment: ${GITHUB_TOKEN}
